#
#
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
# Add configuration values here, as shown below.
# production:
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK

AWS_BUCKET: colaboramerica
AWS_KEY: AKIAJ4TPMYFOHJUQEWTA
AWS_SECRET: 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

# AWS_KEY: AKIAJN5N54A2CFVUH2KA
# AWS_SECRET: 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


COMPANY_ADDRESS_1: 
COMPANY_ADDRESS_2: 
COMPANY_ADDRESS_3: 
COMPANY_CONTACT_MAIL: 
COMPANY_FACEBOOK_PAGE: 
COMPANY_PHONE_NUMBER: 
COMPANY_TWITTER_ACCOUNT: 

DISPLAYED_CURATORS: "20"
DISPLAYED_FEATURED: "20"
DISPLAYED_JURY: "20"
DISPLAYED_SPEAKERS: "20"
DISPLAYED_TEAM_MEMBERS: "20"

EVENTBRITE_APP_KEY: "0000"
EVENTBRITE_ATTENDEES_DISPLAY_NUMBER: "000"
EVENTBRITE_EVENT_ID: "000"
EVENTBRITE_USER_KEY: "000"

FACEBOOK_APP_SECRET: 
FACEBOOK_APP_SECRET_DEV: 

GA_CREDENTIALS: 

MAILER_DOMAIN: 
MAILER_PASSWORD: 
MAILER_SMTP_ADDRESS: 
MAILER_USERNAME: 

OUISHARE_FEST_EVENT_YEAR: '2016'

TRANSIFEX_BASE_URL: 
TRANSIFEX_CREDENTIAL_SECRET: 
TRANSIFEX_INDIVIDUALS_URL: 
TRANSIFEX_OUISHARE_URL: 

YAML_INDIVIDUALS_FILE_PATH: 'config/locales/individuals.yml'
YAML_OUISHARE_FILE_PATH: 'config/locales/dynamic.yml'
